### ISSUE TITLE
[0.2.7] COnfiguration POPReptile / POPAmphibien

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#124]
Bonjour,

J'ai une erreur 500 lors de la configuration du module POPAmphibien ou POPReptile : 

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
     File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 106, in __check_cruved_scope_monitoring
        return fn(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
        res = fn(*args, **kwargs)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 113, in update_object_api
        return create_or_update_object_api(module_code, object_type, id)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 99, in create_or_update_object_api
        .create_or_update(post_data)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 136, in create_or_update
        .format(self, str(e))
    geonature.utils.errors.GeoNatureError: MONITORING: create_or_update monitoringobject popamphibien, module, 81 : 'b_draw_sites_group'
    [2021-11-10 13:33:08 +0100] [1153] [ERROR] Exception on /monitoring/object/popamphibien/module [PATCH]
    Traceback (most recent call last):
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 121, in create_or_update
        self.populate(post_data)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/serializer.py", line 187, in populate
    self.unflatten_specific_properties(properties)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/serializer.py", line 60, in unflatten_specific_properties
        val = properties.pop(attribut_name)
    KeyError: 'b_draw_sites_group'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 106, in __check_cruved_scope_monitoring
        return fn(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
        res = fn(*args, **kwargs)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 113, in update_object_api
        return create_or_update_object_api(module_code, object_type, id)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 99, in create_or_update_object_api
        .create_or_update(post_data)
      File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 136, in create_or_update
        .format(self, str(e))
    geonature.utils.errors.GeoNatureError: MONITORING: create_or_update monitoringobject popamphibien, module, 81 : 'b_draw_sites_group'

Ça parle de `b_draw_sites_group` qui je vois est présent dans `module.json`. Qu'est-ce que c'est ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Non mentionné dans la note de version de la dernière release, as-tu bien lancé le script d'update de la BDD en montant vers la dernière version ? 

https://github.com/PnX-SI/gn_module_monitoring/blob/master/data/migration/migration_0.2.6_0.2.7.sql

**Comment by camillemonchicourt** [comment]
Si il y a bien les notes de version dans la Release : https://github.com/PnX-SI/gn_module_monitoring/blob/master/docs/changelog.rst
Mais cette fois elles sont au début, alors que normalement on les met à la fin :-)

**Comment by DonovanMaillard** [comment]
grrr, le problème des habitudes, c'est qu'on a bien du mal à les changer ! je prends de l'age... merci en tous cas ;) 

Dans tous les cas pour MaximeToma c'est sans doute ce soucis, je suis tombé sur la même erreur avec cette raison ;)

**Comment by maximetoma** [comment]
Alors je vais mettre la mauvaise ambiance mais ça m'affiche l'erreur alors que j'avais effectivement exécuté le script avant :)

**Comment by DonovanMaillard** [comment]
c'est malin... ^^

tu as d'autres logs dans la console, dans le fichier var/log de geonature ? Je les ai installés sur une GN 2.7.5 écemment et je n'ai pas eu de soucis. 

Je suis joignable si tu veux qu'on regarde de vive voix

**Comment by maximetoma** [comment]
Non malheureusement... Le log en entier : 
[geonature.log](https://github.com/PnX-SI/gn_module_monitoring/files/7527489/geonature.log)

Je suis dispo cet aprem

**Comment by joelclems** [comment]
est ce que la variable `b_draw_sites_group` est bien présente dans le fichier `<gn_monitoring>/config/monitoring/generic/module.json`

cf https://github.com/PnX-SI/gn_module_monitoring/blob/787b7c6d8ad8629299ed766f345f5518b4c955ea/config/monitoring/generic/module.json#L108-L113
`

**Comment by maximetoma** [comment]
Aaaaaaaahhhhhhhhhh

Effectivement non !!
J'ai testé de copier le bon fichier et c'est niquel ça marche beaucoup mieux !!

Par contre, mystère quand au fait que j'avais tj l'ancien fichier alors que j'avais télécharger la v.0.2.7...........

Merci :)
