### ISSUE TITLE
[0.2.9] MàJ impossible (Missing conf_gn_module.toml)

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_monitoring#139]
Bonjour, 

J'essaye de [mettre à jour](https://github.com/PnX-SI/gn_module_monitoring/blob/master/docs/MAJ.rst#m%C3%A9thode-classique) le module en version 0.2.9. (avec GeoNature 2.9.1) 

Tout est ok, jusqu'à la commande :
```
source /home/geonatureadmin/geonature/backend/venv/bin/activate
  geonature monitorings process_img
```
qui aboutit à cette erreur :
```
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 33, in <module>
    sys.exit(load_entry_point('geonature', 'console_scripts', 'geonature')())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1653, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1700, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/geonatureadmin/geonature/backend/geonature/app.py", line 164, in create_app
    for module_object, module_config, module_blueprint in import_backend_enabled_modules():
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 104, in import_backend_enabled_modules
    yield import_gn_module(module_object)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 90, in import_gn_module
    module_config, module_blueprint = import_legacy_module(module_object)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 37, in import_legacy_module
    module_config.update(load_and_validate_toml(config_path, module_schema))
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 15, in load_and_validate_toml
    toml_config = load_toml(toml_file)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 28, in load_toml
    raise GeoNatureError("Missing file {}".format(toml_file))
geonature.utils.errors.GeoNatureError: Missing file /home/geonatureadmin/geonature/external_modules/monitorings/config/conf_gn_module.toml
```

Idem avec la commande 
```
geonature update_module_configuration MONITORINGS
```

Si je reviens dans le dossier de la version antérieure utilisée (ici, la  0.2.7), et que je relance les commandes, tout se passe bien.

Il manque des commandes pour la mise à jour dans ce qui est documenté ?

**Comment by camillemonchicourt** [comment]
Salut, j'ai testé une installation de la version 0.2.9 du module avec une version 2.9 et ça a bien fonctionné.
Mais pas testé de mise à jour du module.

@amandine-sahl, @joelclems il y a une évolution au niveau de GeoNature ou du module qui fait que les commandes de mise à jour du module auraient changé ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

avez-vous bien copié le fichier de configuration du module depuis le repertoire gn_module_monitoring_old vers gn_module_monitoring ?

**Comment by DonovanMaillard** [comment]
effectivement, dans la doc on récupère les sous-modules mais pas la conf du module. 

Il faut donc ajouter : 
`cp gn_module_monitoring_old/config/conf_gn_module.toml gn_module_monitoring/config` 

avant de lancer les commandes d'update des configurations et des images a priori :)

**Comment by camillemonchicourt** [comment]
Oui bien vu, le message d'erreur est assez clair, j'avais pas fait attention.
Et en effet la doc de MAJ (https://github.com/PnX-SI/gn_module_monitoring/blob/master/docs/MAJ.rst) oublie de rappeler de récupérer son fichier de conf de la version précédente, ce qu'on indique habituellement dans les docs de MAJ des modules.

**Comment by Splendens** [comment]
Ah bah oui, tout de suite ça fonctionne beaucoup mieux !
C'est ça, dans toutes les docs la ligne de copie de la config est présente... et j'étais tellement sûre de l'avoir lancé que je me demandais pourquoi il ne voulait pas trouver la config (oups...)

-----------
J'ai recommencé depuis le début, cette fois j'ai bien copié le fichier de config avant de lancer les updates. Pour les images, pas d'erreurs. Mais la commande d'update de la config aboutit à ça :

`ERROR in ../external_modules/monitorings/frontend/app/components/monitoring-properties/monitoring-properties.component.ts(7,25): error TS2307: Cannot find module 'html2canvas'.`

Même problème que celui décrit ici : https://github.com/PnX-SI/gn_module_monitoring/issues/119 sauf que la solution proposée ne fonctionne pas ici (je peux lancer les updates sans erreurs, mais le module ne fonctionne pas)

_(le souci n'a plus rien à voir, je clos le ticket pour en ouvrir un autre dédié au nouveau pb ?)_

**Comment by camillemonchicourt** [comment]
Je ne vois pas la mention de copier la conf dans la doc : https://github.com/PnX-SI/gn_module_monitoring/blob/master/docs/MAJ.rst
A rajouter selon moi.

Il n'est pas indiqué dans la doc (ni conseillé à mon avis) de mettre ses sous-module dans le dossier ``contrib`` du module Monitoring, justement car cela oblige à les rapatrier à chaque mise à jour du module.
Chacun les met où il souhaite.
De notre côté on a un dossier dédié à la racine du ``home`` de l'utilisateur, à côté des dossiers de GeoNature, TaxHub, UserHub et des modules de GeoNature.
