### ISSUE TITLE
[0.2.10] Suppression de site impossible via l'interface

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_monitoring#173]
**Version**
Monitoring 0.2.10

**Description du bug**
Lorsqu'on veut supprimer un site via l'interface, la pop-up "suppression du site effectuée" apparait, mais il n'est pas supprimé en base, et il y a une erreur 500 qui apparait dans la console. 

Dans les log de Geonature, on trouve : 

```
[2022-06-02 12:58:16 +0200] [24386] [ERROR] Exception on /monitorings/object/suiviloutrelocal/site/46133 [DELETE]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 150, in delete
    DB.session.commit()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 538, in execute
    self.dependency_processor.process_deletes(uow, states)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 1105, in process_deletes
    uowcommit, secondary_insert, secondary_update, secondary_delete
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 1207, in _run_crud
    result.rowcount,
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 't_site_complements' expected to delete 3 row(s); Only 2 were matched.

```

En revanche, aucun problème pour supprimer un site directement en SQL, avec la commande 

```
DELETE FROM gn_monitoring.t_base_sites
WHERE id_base_site <l'id du site> 
```

**Comment by joelclems** [comment]
bonjour marie

que donne la requete
```
select count(*) from gn_monitoring.t_site_complements where id_base_site=46133

```

?

**Comment by Splendens** [comment]
Bonjour, 
Cette requête donne "1".

Pour compléter la description de l'erreur, cela semble venir des groupe de sites. Lorsque le site que je veux supprimer est lié à un groupe de sites, impossible de le supprimer via l'interface. Par contre, pas de problème de suppression si le site n'est pas lié à un groupe.
