### ISSUE TITLE
[Gestion Droits] Erreur lors de la Suppression d'un site 

### ISSUE THREAD

**Issue by pierre56** [PnX-SI/gn_module_monitoring#216]
# Erreur droits Suppression

## Tickets reliés ?
https://github.com/PnX-SI/gn_module_monitoring/issues/1
https://github.com/PnX-SI/gn_module_monitoring/issues/92
https://github.com/PnX-SI/gn_module_monitoring/issues/173

## Contexte

Bonjour,
après avoir installé le module https://github.com/DonovanMaillard/popamphibien de @DonovanMaillard .
J'ai créé un groupe référents qui a des droits élevés pour voir, valider et exporter toutes les obs.
Nous avons entamé la phase de test avant d'ouvrir a une centaine d'utilisateurs.
Et un de mes référents a trouvé a rencontré une erreur problématique. 

## Versions
geonature : 2.10.4
monitoring : 0.3.0
Module PopAmphibien 1.0.0

## Error 1

Un utilisateur ayant les droits de suppression 1 n'a pas pu supprimer un site alors que c'est lui qui l'a créé.
Je précise qu'il n'y avait pas encore de passage ou d'obs sur ces sites. 

### LOG
```

[2023-03-03 14:22:01 +0100] [1503] [ERROR] Exception on /MONITORINGS/object/POPAmphibien/site/66 [DELETE]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 93, in __check_cruved_scope_monitoring
    raise InsufficientRightsError(
pypnusershub.db.tools.InsufficientRightsError: ('User 57 with permission level 1 for action D is not allowed to use this route for module POPAmphibien, min permission level is 3', 403)

```

### Todo
Modifier la route ?

## Error 2
Me disant qu'il s'agissait d'une erreur de droits.
J'ai fait comme le demandait le log et ai passé le droit delete a 3 pour mon user.

Après avoir demandé a la personne de reproduire la manip.
Le site a bien été supprimé, mais également l'aire ... :/

### Log gn_commons.t_history_actions
```

{
  "id_base_site": 66,
  "id_inventor": 57,
  "id_digitiser": 57,
  "id_nomenclature_type_site": 446,
  "base_site_name": "La_Motte_05",
  "base_site_description": null,
  "base_site_code": null,
  "first_use_date": "2023-02-20",
  "geom": {
    "type": "Point",
    "coordinates": [
      -1.359333,
      47.617529
    ]
  },
  "geom_local": {
    "type": "Point",
    "coordinates": [
      372702.94167372776,
      6733164.449441973
    ]
  },
  "altitude_min": null,
  "altitude_max": null,
  "uuid_base_site": "be7ab3bb-0692-44bd-8eb2-dd8954c4cbaa",
  "meta_create_date": "2023-03-03T12:17:18.175793",
  "meta_update_date": null
}
```

Étonnement, dans la table  t_base_sites, les autres sites n'ont pas été impactés et sont toujours présents.
Par contre dans la table t_sites_groups, l'aire a disparu.
Ce qui fait que le groupe de site n'est plus visible dans l'interface de geonature.

### Log
```
[d53015b2-d259-44b8-ab8b-43414059ec5a] Exception on /MONITORINGS/breadcrumbs/POPAmphibien/sites_group/17 [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 43, in get
    req
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 106, in __check_cruved_scope_monitoring
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 166, in breadcrumbs_object_api
    monitoring_definitions
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 53, in get
    raise GeoNatureError('MONITORING : get_object : {}'.format(e))
geonature.utils.errors.GeoNatureError: MONITORING : get_object : No row was found for one()
```

Après recréation de l'aire et mise a jours de l'id dans t_site_complements.
J'ai réussi a rattacher les sites a l'aire et afficher aire + site dans l'interface.

# Comportement attendu du module

Si droit D a 1, suppression du site si la personne est l'auteur, sans suppression de l'aire.

L'erreur est-elle liée a la version que j'utilise ou encore a corriger ?

Merci 😄

**Comment by pierre56** [comment]
Merci pour la réponse très rapide @DonovanMaillard 
D'habitude, je créé un ticket par pb, mais cela me paraissait pertinent d'avoir le fil des étapes et différents pb sur le mm ticket pour comprendre la logique^^

Pour le moment, le soucis est résolu et j'ai repassé les droits a 1 de mes users pour éviter de refaire l'erreur  donc pb n°1 plus existant mais a résoudre car je vais pas pouvoir gérer si on me demande une inter en bdd a chaque suppression de site 😓 .

Pour le pb 2,
Je vais essayer de trouver de mon côté également la semaine pro et je vais créer un ticket séparé si j'arrive a trouver des pistes intéressantes.
Il faut d'abord que je fasse la maj de geonature en 2.11, puis celle de monitoring , et également celle du module Pop Reptile.
C'est peut être juste une erreur de version 😅
