### ISSUE TITLE
Conseils pour la configuration des fichiers .json

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/gn_module_monitoring#246]
Bonjour à tous, 

Je me suis lancée dans la configuration d'un sous-module pour le protocole ICOCAM (Module de suivi de l'Indicateur composite coléoptères aquatiques des mares). Je galère un peu mais j'ai réussi à afficher un premier formulaire pour la description des sites. Cependant j'ai des champs (code, description, type de site) qui étaient décrit dans le fichier exemple site.json et qui restent dans mon formulaire. il y a dans la liste `type de sites` la valeur `site Rhomeo Odonates`, car j'ai installé le module en exemple pour comprendre comment rédiger le .json. Donc il y a un lien quelque part mais je ne le comprends pas vraiment...

![bug_site_json](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/70c885c3-bbc7-468b-8314-c13cab48b11f)
![bug_site_json2](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/d864535c-306a-4ee9-ac86-e0d245b26bf4)
Comment faire (où dois-je aller dans les fichiers) pour supprimer ces champs ? Je vous mets en fin de message mon fichier site.json.

J'aimerais aussi des conseils pour les champs conditionnels. Je peux afficher un champ en fonction de la valeur d'un autre champ, ça c'est bon. Mais dans ICOCAM, pour chaque passage, il faut décrire les milieux (mésohabitats) et indiquer pour chaque milieu une surface en %.
J'ai donc une liste `multiselect`, et à chaque choix, le champ `surface` doit "apparaître" ou "être lié".
Je ne sais pas comment écrire ça (est-ce possible d'ailleurs ?), le nombre de milieux n'étant pas limité (la limite étant le nombre max de milieux dans la liste). 
En gros, ce serait comme remplir un tableau avec les habitats présents et leur surface relative.
J'ai regardé quelques autres fichiers .json dans les exemples de modules disponibles mais je n'ai pas trouvé quelque chose de similaire.

Merci d'avance pour votre aide,
Bonne journée,
Vottana

```
{
  "cruved": {"C":3, "R":3, "U":1, "V":0, "E":3, "D": 1},
  "genre":"F",
  "label": "mare",
  "label_list": "Mares",
  "geometry_type": "Point",
  "map_label_field_name": "base_site_name",
  "export_pdf": [
      { "template": "fiche_mare.html", "label": "Export PDF" }
  ],
  "sorts": [
    {"prop": "base_site_name", "dir": "asc"}
  ],
  "display_properties": [
    "base_site_name",
    "id_inventor",
    "first_use_date",
    "lieu_dit",
    "longueur_m",
    "largeur_m",
    "forme",
	  "regime_hydro",
	  "origine_mare",
	  "liaison_hydro",
	  "topographie",
	  "topographie_autres",
	  "contexte",
    "contexte_autres",
	  "materiel_interdiction",
	  "distance_voie_pub",
  	"usage_principal",
	  "contexte_foncier",
	  "contexte_foncier_detail",
  	"infos_gestion"
 ],
  "display_list": [
    "base_site_name",
	  "lieu_dit",
    "id_inventor",
    "first_use_date",
    "nb_visits"
  ],
  "specific": {
    "lieu_dit": {
      "type_widget": "text",
      "attribut_label": "Lieu-dit",
      "hidden": false
	},
    "longueur_m": {
      "type_widget": "number",
      "attribut_label": "Longueur (en m)"
    },
    "largeur_m": {
      "type_widget": "number",
      "attribut_label": "Largeur (en m)"
    },
    "forme": {
	  "type_widget": "radio",
      "attribut_label": "Forme",
      "values": ["ronde/ovale","triangle carré/rectangle","patatoïde","complexe (digitée, en U)"]
	},
	"regime_hydro":{
	  "type_widget": "radio",
      "attribut_label": "Régime hydrologique, selon l'observateur",
      "values": ["mare permanente présumée","mare permanente avec certitude","mare temporaire présumée","mare temporaire avec certitude"]
	},
	"origine_mare":{
	  "type_widget": "radio",
      "attribut_label": "Mare sur une source ou insérée sur écoulement",
      "values": ["oui","non"]
	},
	"liaison_hydro":{
	  "type_widget": "radio",
      "attribut_label": "Liaison avec le réseau hydrographique",
      "values": ["écoulement actif en sortie","écoulement à sec en sortie","pas d’écoulement en sortie"]
	},
	"topographie":{
	  "type_widget": "radio",
      "attribut_label": "Topographie",
      "values": ["plateau/plaine","versant","fond de vallée","littoral","autres : texte libre"]
	},
	"topographie_autres":{
	  "type_widget": "text",
      "attribut_label": "Autres types de topographie",
      "hidden": "({value}) => value.topographie != 'autres : texte libre'"
	},
 "contexte":{
	  "type_widget":"multiselect",
	  "attribut_label":"Contexte (plusieurs choix possibles en fonction de l’échelle et de la complexité du site)",
	  "values": ["arrière-littoral (dunaire)","bassins artificiels (annexe routière, etc.)","boisement feuillus","boisement résineux","carrières","complexes de marais","cultures","falaises et rochers littoraux",
	  "fossés","gouille temporaire","haies","lande humide ou tourbeuse","lande sèche ou mésophile","milieux urbanisés","ornières","pelouses sèches et ourlets","prairie humide","prairie mésophile",
	  "ripisylve et annexe fluviale","saulaie marécageuse","tourbière et prairie tourbeuse","vergers", "autres (précision)"]
	},
 "contexte_autres":{
    "type_widget": "text",
    "attribut_label": "Autres contextes",
    "hidden": "({value}) => value.contexte != 'autres (précision)'"
	},
 	"materiel_interdiction":{
	  "type_widget": "radio",
      "attribut_label": "Matérialisation d’interdiction d’accès à la parcelle (panneau, grillage …)",
      "values": ["oui","non"]
	},
    "distance_voie_pub":{
	  "type_widget": "number",
      "attribut_label": "Distance de la voie publique la plus proche (approximation en m)"
	},
	"usage_principal":{
	  "type_widget": "multiselect",
      "attribut_label": "Usage principal de la mare (plusieurs choix possibles)",
      "values": ["abreuvement direct","abreuvement indirect","collecte ruissellement","incendie","pêche","chasse","ornemental","biodiversité/patrimoine","abandonné","pédagogique","ne sais pas"]
	},
	"contexte_foncier":{
	  "type_widget": "radio",
      "attribut_label": "Contexte foncier",
      "values": ["public","privé","ne sais pas"]
	},
	"contexte_foncier_detail":{
	  "type_widget": "textarea",
      "attribut_label": "Détail si le contexte foncier est inconnu",
      "hidden": "({value}) => value.contexte_foncier != 'ne sais pas'"
	},
	"infos_gestion":{
	  "type_widget": "textarea",
          "attribut_label": "Information sur la gestion et historique de la pièce d’eau"
	}
   }
}

```

**Comment by amandine-sahl** [comment]
> Cependant j'ai des champs (code, description, type de site) qui étaient décrit dans le fichier exemple site.json et qui restent dans mon formulaire.

Ces champs sont les champs de « base » de la description des sites, nom et code sont obligatoire.

Pour cacher un champ il est possible d’utiliser la valeur `"hidden": true`

**type de site**
Pour ne pas voir apparaitre le type de site `Rhomeo Odonates` il faut le supprimer dans la table nomenclature ou limiter les valeurs possible en indiquant la liste des codes nomenclature que l'on souhaite

exemple 
```json
    "id_nomenclature_bio_status": {
      "type_widget": "nomenclature",
      "attribut_label": "Statut biologique",
      "code_nomenclature_type": "STATUT_BIO",
      "type_util": "nomenclature",
      "required": true,
      "value": {
        "code_nomenclature_type": "STATUT_BIO",
        "cd_nomenclature": "0"
      },
      "cd_nomenclatures": ["3", "4", "9", "0", "1" ]

    },
```



**champs conditionnels**
Personnellement je ne vois pas non plus comment faire dans ce cas là. Les champs doivent être prédéfini et ne peuvent pas être générés à la volée. 

S'il y a un nombre maximal d'habitat possible non exhorbitant, j'aurais tendance à multiplier le champ surface de l'habitat. 
exemple surface_habitat_1, surface_habitat_2, ...,  surface_habitat_n

**Comment by Vottana** [comment]
Bonjour à tous,

Je reste bloquée avec la partie Habitat à décrire. Suite au conseil d'Amandine, je vais créer un champ avec sa surface pour un nombre d'habitat défini.
Voilà dans l'idée ce que je voudrais faire :
```
champ Habitat 1 à choisir dans ma liste, avec valeur par défaut 'Aucun'
si Habitat 1 != 'Aucun' => surface_habitat 1
si surface_habitat 1 > 0 => champ Habitat 2 à choisir dans la liste
si champ Habitat 2 != 'Aucun' => surface_habitat 2
etc.
```
Comme ça les champs apparaissent au fur et à mesure, pour éviter un formulaire trop long dès le départ.
Mais je bloque sur mon champ Habitat.
Je n'arrive pas à faire fonctionner mon `visit.json` en utilisant la nomenclature pour les habitats. Il fonctionne si je ne mets pas ce champ.

Tous mes habitats son décrits dans `nomenclature.json` et j'ai mis à jour la base de données. Les habitats sont bien visibles dans la nomenclature en passant par le backoffice de Geonat. J'ai également fait un `restart` au besoin. 
Mes habitats sont décrit ainsi dans `nomenclature.json` : 

```
  "types": [
    {
      "mnemonique": "MESOHABITAT_AQUA",
      "label_default": "Mésohabitat du compartiment aquatique (2 m à 30 cm de profondeur)",
      "definition_default": "Mésohabitat du compartiment aquatique (2 m à 30 cm de profondeur)du protocole de suivi ICOCAM"
    },
    {
      "mnemonique": "MESOHABITAT_EAU_TERRE",
      "label_default": "Mésohabitats de l’interface eau-terre (de 30 cm de profondeur à la berge)",
      "definition_default": "Mésohabitat de l'interface eau-terre (de 30 cm de profondeur à la berge) du protocole de suivi ICOCAM"
    }
  ],
  "nomenclatures": [
    {
      "type":"MESOHABITAT_AQUA",
      "cd_nomenclature": "A0",
      "mnemonique": "aq_aucun ",
      "label_default": "Aucun",
      "definition_default": "Valeur par défaut, aucun habitat décrit"
    },
  {
      "type":"MESOHABITAT_AQUA",
      "cd_nomenclature": "A1a1",
      "mnemonique": "aq_laciniees ",
      "label_default": "A1a1-A1a4. Hydrophytes|Feuilles laciniées et/ou feuilles filiformes et/ou larges feuilles entières et/ou petites feuilles entières",
      "definition_default": "Mésohabitat du compartiment aquatique|Hydrophytes|Submergés (A1a)|feuilles laciniées (ex : Myriophyllum sp., Utricularia sp., Ceratophyllum sp., Ranunculus sp.) et/ou feuilles filiformes (ex : Potamogeton pusillus, P. pectinatus, Zannichellia palustris) et/ou larges feuilles entières (ex : Potamogeton crispus, P. lucens, P. perfoliatus) et/ou petites feuilles entières (ex : Elodea sp.)"
    },
	{
      "type":"MESOHABITAT_AQUA",
      "cd_nomenclature": "A1a5",
      "mnemonique": "aq_characees",
      "label_default": "A1a5. Hydrophytes|Characées (toutes espèces)",
      "definition_default": "Mésohabitat du compartiment aquatique|Hydrophytes|Submergés (A1a)|Characées (toutes espèces)"
    },
```
etc. jusqu'au 40e habitat.

Dans mon fichier `visit.json`, je définis les habitats ainsi : 
```
 "id_nomenclature_hab1":{
    "type_widget": "nomenclature",
    "attribut_label": "Mésohabitat n°1 du compartiment aquatique (2 m à 30 cm de profondeur)",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	"required": true
```
1ère question : 
En lisant la documentation et les exemples, je ne comprends pas différence entre le widget datalist et nomenclature : le widget datalist est une liste définie par la nomenclature en utilisant l'api nomenclature mais le widget nomenclature n'utilise pas l'api ? Est-ce qu'on peut utiliser l'un ou l'autre sans distinction où il y a des cas où l'un est mieux que l'autre ?

2e question : 
mon fichier renvoie un message d'erreur et le log donne ça : 
```
[2023-09-18 15:32:23 +0200] [1599968] [ERROR] Exception on /monitorings/config/icocam [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/gn_module_monitoring/backend/gn_module_monitoring/routes/config.py", line 20, in get_config_api
    return get_config_frontend(module_code, force=True)
  File "/home/geonatureadmin/gn_module_monitoring/backend/gn_module_monitoring/config/repositories.py", line 241, in get_config_frontend
    config = dict(get_config(module_code, force))
  File "/home/geonatureadmin/gn_module_monitoring/backend/gn_module_monitoring/config/repositories.py", line 162, in get_config
    config['data'] = get_data_preload(config, module)
  File "/home/geonatureadmin/gn_module_monitoring/backend/gn_module_monitoring/config/utils.py", line 282, in get_data_preload
    out['nomenclature'].append(form['code_nomenclature_type'])
KeyError: 'code_nomenclature_type'
```
Je vois l'erreur sur le `code_nomenclature_type`, mais je ne vois pas ce que je fais de travers ?

Merci d'avance pour votre aide.

Bonne journée,
Vottana

**Comment by joelclems** [comment]
il faut ajouter la clé    `code_nomenclature_type` dans la définition de `id_nomenclature_hab1`
```
 "id_nomenclature_hab1":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA"
    "attribut_label": "Mésohabitat n°1 du compartiment aquatique (2 m à 30 cm de profondeur)",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	"required": true
```

**Comment by Vottana** [comment]
Aaaaah merci !
Je l'avais supprimé car pour les sites, `code_nomenclature_type` n'est indiqué qu'une seule fois : 
```
"id_nomenclature_type_site": {
      "attribut_label": "Type site",
      "type_util": "nomenclature",
      "value": {
          "code_nomenclature_type": "TYPE_SITE",
          "cd_nomenclature": "site_icocam"},
      "hidden": true
    }
```
C'est parce que ce n'est pas une liste dans le cas des sites, mais juste une valeur unique, par défaut ?

**Comment by Vottana** [comment]
Bonjour à tous, 

j'ai pu créer mes champs Habitat et surface, qui apparaissent au fur et à mesure, mais j'ai une question sur l'ordre d'apparition.
Dans display_properties mes champs sont ordonnés ainsi :
```
"id_nomenclature_hab1",
  "surface_hab1",
  "id_nomenclature_hab2",
  "surface_hab2"
  "id_nomenclature_hab3",
  "surface_hab3",
  "id_nomenclature_hab4",
  "surface_hab4",
  "id_nomenclature_hab5",
  "surface_hab5"
```
Avec la surface à la suite du mésohabitat correspondant. Dans la description, je les décris dans ce même ordre :  
```
"id_nomenclature_hab1":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat n°1 du compartiment aquatique (2 m à 30 cm de profondeur)",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      }
   },
  "surf_hab1":{
    "type_widget": "number",
    "attribut_label": "Surface relative du mésohabitat aquatique n°1 en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab1] || {}).cd_nomenclature == 'A0'}"  
   },
  "id_nomenclature_hab2":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat n°2 du compartiment aquatique (2 m à 30 cm de profondeur)",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab1 === null"
    },
   "surf_hab2":{
    "type_widget": "number",
    "attribut_label": "Surface relative du mésohabitat aquatique n°2 en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab2] || {}).cd_nomenclature == 'A0'}"
    },
    "id_nomenclature_hab3":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat n°3 du compartiment aquatique (2 m à 30 cm de profondeur)",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab2 === null"
    },
   "surf_hab3":{
    "type_widget": "number",
    "attribut_label": "Surface relative du mésohabitat aquatique n°3 en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab3] || {}).cd_nomenclature == 'A0'}"
    },
```
Mais à l'affichage, tous les habitats s'affichent au-dessus, toutes les surfaces de l'autre. Ce n'est pas grave en soit mais c'est un peu déstabilisant à la saisie car le champ suivant apparait à la saisie du champ précédent. On a donc un champ habitat qui apparait au-dessus, la surface correspondante qui apparait en dessous des surfaces précédentes, bref c'est un peu brouillon, surtout si j'ai beaucoup d'habitat.

![ordre_champs_visit](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/ade0cb89-1d09-4412-b634-0ef315a26144)

Est-ce qu'il y a une solution pour forcer l'ordre d'affichage des champs ?
 
Merci d'avance !

**Comment by joelclems** [comment]
En utilisant `display_properties` on peut forcer l'ordre (un tableau contenant le nom des champs)

**Comment by Vottana** [comment]
Dans `display_properties` mes champs sont ordonnés dans l'ordre que je souhaite mais l'affichage ne suit pas cet ordre : 
```
"display_properties": [
  "id_nomenclature_hab1",
  "surface_hab1",
  "id_nomenclature_hab2",
  "surface_hab2",
  "id_nomenclature_hab3",
  "surface_hab3",
  "id_nomenclature_hab4",
  "surface_hab4",
  "id_nomenclature_hab5",
  "surface_hab5"
  ],
```

Ce n'est pas comme ça qu'il faut faire ?

**Comment by joelclems** [comment]
Pouvez poster le fichier entier ?

**Comment by Vottana** [comment]
Bien sûr, merci pour ton aide !

```
{
  "cruved": {"C":3, "R":3, "U":1, "V":0, "E":3, "D": 1},
  "genre":"M",
  "label": "Passage",
  "label_list": "Passage",
  "display_properties": [
  "observers",
	"visit_date_min",
	"num_passage",
	"observeurs",
	"temperature",
	"ph",
	"profondeur_today",
	"profondeur_max",
	"ombrage",
	"boisement",
	"berges",
	"evolution",
	"bourrelet",
	"bourrelet_pourcent",
	"eau",
	"fond",
	"surpietinement",
	"echantillonnage",
	"echantillonnage_difficile",
	"indesirables",
	"invasives",
	"poissons",
	"amphibiens",
	"invertebres",
	"vegetaux",
	"densite",
	"taille",
	"id_nomenclature_hab1",
  "surface_hab1",
  "id_nomenclature_hab2",
  "surface_hab2",
  "id_nomenclature_hab3",
  "surface_hab3",
  "id_nomenclature_hab4",
  "surface_hab4",
  "id_nomenclature_hab5",
  "surface_hab5"
  ],
 "specific":{
 "comments":{
   "hidden":true
   },
  "id_dataset": {
    "type_widget": "dataset",
    "hidden":true
  }, 
	"num_passage":{
		"type_widget": "radio",
		"attribut_label": "Numéro de passage (obligatoire)",
		"values": [1, 2],
		"required": true
	},	
	"temperature":{
		"type_widget": "number",
		"attribut_label": "Température en C°"
	},
	"ph":{
		"type_widget": "number",
		"attribut_label": "pH"
	},
	"profondeur_today":{
		"type_widget": "select",
		"attribut_label": "Profondeur d'eau aujourd'hui",
		"values": ["à sec","< 30 cm","30-60 cm","60-100 cm",">100 cm"]
	},
	"profondeur_max":{
		"type_widget": "select",
		"attribut_label": "Profondeur d'eau maximale évaluée",
		"values": ["à sec","< 30 cm","30-60 cm","60-100 cm",">100 cm"]
	},
	"ombrage":{
		"type_widget": "select",
		"attribut_label": "Ombrage surface par ligneux (soleil au zénith)",
		"values": ["0%","<25%","25–50%","50–75%","75–99%","100%"]
	},
	"boisement":{
		"type_widget": "select",
		"attribut_label": "Boisement/embrouissaillement des abords",
		"values": ["0%","<25%","25–50%","50–75%","75–99%","100%"]
	},
	"berges":{
		"type_widget": "select",
		"attribut_label": "Berges en pente douce (% en périmètre)",
		"values": ["0%","<25%","25–50%","50–75%","75–99%","100%"]
	},
	"evolution":{
		"type_widget": "select",
		"attribut_label": "Stade d'évolution de la mare",
		"values": ["1 : pionnier (récemment curée, par exemple)",
				   "2 : végétation enracinée avec eau libre",
				   "3 : saturée à 100% de végétation herbacée enracinée",
				   "4 : partiellement dissimulée sous ronces / ligneux",
				   "5 : entièrement sous les ronces / ligneux"]
	},
	"bourrelet":{
		"type_widget": "radio",
		"attribut_label": "Bourrelet de curage en haut de berge",
		"values": ["oui","non"]
	},
	"bourrelet_pourcent":{
		"type_widget": "number",
		"attribut_label": "Longueur du bourrelet en % du périmètre",
		"hidden": "({value}) => value.bourrelet != 'oui'"
	},
	"eau":{
		"type_widget": "radio",
		"attribut_label": "Eau",
		"values": ["trouble","limpide"]
	},
	"fond":{
		"type_widget": "radio",
		"attribut_label": "Fond",
		"values": ["portant","non portant","mixte"]
	},
	"surpietinement":{
		"type_widget": "radio",
		"attribut_label": "Surpiétinement des abords",
		"values": ["intense et total","localisé","faible à nul"]
	},
	"echantillonnage":{
		"type_widget": "radio",
		"attribut_label": "Conditions d’échantillonnage de la pièce d’eau (accès, pratique du troubleau, etc.)",
		"values": ["facile","moyenne","difficile (préciser)"]
	},
	"echantillonnage_difficile":{
		"type_widget": "radio",
		"attribut_label": "Détail si échantillonnage difficile",
		"hidden": "({value}) => value.echantillonnage != 'difficile (préciser)'"
	},
	"indesirables":{
		"type_widget": "select",
		"attribut_label": "Présence d'indésirables",
		"values": ["aucun","déchets","remblais","autres (préciser)"],
		"hidden": "({value}) => value.indesirables != 'autres (préciser)'"
	},
	"invasives":{
		"type_widget": "radio",
		"attribut_label": "Présence d'espèces invasives",
		"values": ["oui (à préciser dans la fiche Observation)","non","ne sais pas"]
	},
	"poissons":{
		"type_widget": "radio",
		"attribut_label": "Présence de poissons",
		"values": ["oui (à saisir dans Occtax)","non","ne sais pas"]
	},
	"amphibiens":{
		"type_widget": "radio",
		"attribut_label": "Présence d'amphibiens",
		"values": ["oui (à saisir dans Occtax)","non","ne sais pas"]
	},
	"invertebres":{
		"type_widget": "radio",
		"attribut_label": "Présence d'invertébrés autres que coléoptères aquatiques",
		"values": ["oui (à saisir dans Occtax)","non","ne sais pas"]
	},
	"vegetaux":{
		"type_widget": "radio",
		"attribut_label": "Présence d'espèces végétales remarquables",
		"values": ["oui (à saisir dans Occtax)","non","ne sais pas"]
	},
	"densite":{
		"type_widget": "select",
		"attribut_label": "Densité relative en invertébrés (estimation subjective après échantillonnage, demande un peu d’expérience)",
		"values": ["très faible","faible","moyenne","élevée","très élevée"]
	},
  "taille":{
		"type_widget": "number",
		"attribut_label": "Taille de la mare (en date de la prospection, en m²)"
	},
  "id_nomenclature_hab1":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat aquatique n°1",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      }
   },
  "surf_hab1":{
    "type_widget": "number",
    "attribut_label": "Mésohabitat aquatique n°1 - surface relative en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab1] || {}).cd_nomenclature == 'A0'}"  
   },
  "id_nomenclature_hab2":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat aquatique n°2",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab1 === null"
    },
   "surf_hab2":{
    "type_widget": "number",
    "attribut_label": "Mésohabitat aquatique n°2 - surface relative en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab2] || {}).cd_nomenclature == 'A0'}"
    },
    "id_nomenclature_hab3":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat aquatique n°3",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab2 === null"
    },
   "surf_hab3":{
    "type_widget": "number",
    "attribut_label": "Mésohabitat aquatique n°3 - surface relative en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab3] || {}).cd_nomenclature == 'A0'}"
    },
	"id_nomenclature_hab4":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat aquatique n°4",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab3 === null"
    },
   "surf_hab4":{
    "type_widget": "number",
    "attribut_label": "Mésohabitat aquatique n°4 - surface relative en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab4] || {}).cd_nomenclature == 'A0'}"
    },
	"id_nomenclature_hab5":{
    "type_widget": "nomenclature",
    "code_nomenclature_type": "MESOHABITAT_AQUA",
    "attribut_label": "Mésohabitat aquatique n°5",
    "type_util": "nomenclature",
  	"value": {
          "code_nomenclature_type": "MESOHABITAT_AQUA",
          "cd_nomenclature": "A0"
				},
	  "required": true,
    "params": {
          "orderby": "cd_nomenclature"
      },
    "hidden": "({value}) => value.surf_hab4 === null"
    },
   "surf_hab5":{
    "type_widget": "number",
    "attribut_label": "Mésohabitat aquatique n°5 - surface relative en %",
    "hidden": "({value, meta}) => {return (meta.nomenclatures[value.id_nomenclature_hab5] || {}).cd_nomenclature == 'A0'}"
    }
  }
 }
```

**Comment by joelclems** [comment]
Est ce que les champs sont bien affichés dans l'ordre voulu dans les propriétés?

**Comment by Vottana** [comment]
Bonjour, je ferme l'issue. Mon problème était tout bête, les surfaces étaient notées `surface_hab` dans les propriétés mais `surf_hab` dans la description. Forcément...
