### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by MoulinZ** [PnX-SI/gn_module_monitoring#312]
Bonjour,

J'ai une erreur lors de l'installation du module sur un geonature tout neuf en 2.13.4 :

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 362cf9d504ec, create_monitoring_schema
INFO  [alembic.runtime.migration] Running upgrade 362cf9d504ec -> 2003e18f248a, Add type to gn_modules
INFO  [alembic.runtime.migration] Running upgrade 2003e18f248a -> e78003460441, Correction t_observation_detail
INFO  [alembic.runtime.migration] Running upgrade e78003460441 -> fc90d31c677f, declare available permissions
INFO  [alembic.runtime.migration] Running upgrade fc90d31c677f -> 3ffeea74a9dd, Rename GNM_ to MONITORINGS_
INFO  [alembic.runtime.migration] Running upgrade 3ffeea74a9dd -> c1528c94d350, Upgrade existing permissions
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "gn_monitoring.t_module_complements" does not exist
LINE 2: FROM gn_commons.t_modules JOIN gn_monitoring.t_module_comple...
```

Il me manque en effet en base de données toutes les tables après t_base_visit (je n'ai que 5 tables).

**Comment by camillemonchicourt** [comment]
Duplicate : https://github.com/PnX-SI/gn_module_monitoring/issues/284
