### ISSUE TITLE
Définition sous-module : erreur à l'exécution

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#90]
Bonjour,
J'ai configuré un nouveau sous module dans montorings (version 2.5.5 de geonature) dans lequel j'ai défini une nomenclature spécifique. je me suis inspiré des exemples donnés sur git.
J'ai une erreur visiblement dans ce module car j'obtient cette erreur dans le log.
[2021-05-05 17:26:38 +0200] [13104] [ERROR] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Exception on /monitorings/util/init_data/sentinelle_odonates [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 23, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/data_utils.py", line 74, in get_init_data
    for nomenclature in nomenclature_list['values']:
TypeError: 'NoneType' object is not subscriptable
[2021-05-05 17:26:50 +0200] [20037] [ERROR] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is ov

**Comment by christianbieche** [comment]
Je vous donne le fichier de nomenclature et le fichier observations qui l'utilise. Cela parait correct pourtant.
question annexe : est-il possible de faire du debug dans le code de l'application en cours et comment  ? Ce  serait plus simple que de faire test, errerur, test à l'aveugle .....
christian bièche
cistude Nature
[mod_odonates.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6428368/mod_odonates.zip)
[mod_odonates.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6428376/mod_odonates.zip)

**Comment by joelclems** [comment]
J'ai pu reproduire l'erreur, 
si flask est en mode debug, quand on va sur l'api qui pose problème on tombe sur une page de debuggage (avec un contenu similaire au premier post)
il faut juste recupérer un code depuis la console

**Comment by joelclems** [comment]
C'est une coquille dans le fichier  `observation.json` pour le champs `grpEsp`

il faut changer "code_nomenclature_type": "GRP_SP_OD" en "code_nomenclature_type": "GRP_SP_ODO",

effectivement il faudrait lever une erreur explicite là dessus

beaucoup de champs pourraient ici utiliser les nomenclatures existantes dans `GN`

**Comment by joelclems** [comment]
Il y aurait peut être quelque chose à faire avec la taxonomie plutot qu'avec les nomenclature pour le champs groupe espece.

**Comment by christianbieche** [comment]
Super merci. je n'avais pas vu la coquille. 

Pour la suggestion dans la nomenclature, effectivement c'est 1 idée auquel j'ai pensé mais ce sont des informations spécifiques à ce module. Après si effectivement cela pose des problèmes de performance pourquoi pas. Cependant je suppose que cela rajoute simplement une liste côté javascript de 50 éléments. 

Et merci pour l'information sur le debug. Je vais cela la prochaine fois. Il suffit de mettre dans confg.py modeDebug = True et de relancer geonature c'est çà ?

**Comment by joelclems** [comment]
pour être en mode debug je fais cette procédure
- je coupe supervisor pour geonature
```
sudo supervisorctl stop geonature
``` 
- au besoin je charge le venv pour avoir la commande `geonature` activée
```
source <geonature_dir>/backend/venv/bin/activate
```
je lance flask avec la commande
```
geonature dev_back
```

**Comment by christianbieche** [comment]
Encore merci. Je ferais cela la prochaine fois avant de poster une issue.
En plus hier j'ai affiché l'aide des commandes geonature et cette commande y était.

Pour info, si cela peut aider les autres, une fois l'environnement virtuel activé (venv) on peut taper geonature --help
ce qui donne la liste des commandes disponibles.

**Comment by joelclems** [comment]
Un des avantage d'utiliser les nomenclatures c'est qu'on peut les utiliser ensuite dans la vue qui permet d'insérer les données dans la synthese.

Je pense aux champs `procObserv`, `sexe`, `statBiolog`, `comportmt`, `denbrType` (à vérifier si on retrouve les champs équivalents dans t_nomenclatures)

**Comment by camillemonchicourt** [comment]
Oui en utilisant les nomenclatures existantes cela permet d'utiliser ces infos pour alimenter des champs existants dans la synthèse, en utilisant des vocabulaires standards et partagés et communs du SINP, donc fortement conseillé quand c'est possible.
